const screens = [...document.querySelectorAll('.screen')];
const music = document.querySelector('#music');
const watched = new Set(JSON.parse(sessionStorage.getItem('birthday-edits-watched') || '[]'));
const cards = Array.from({length:8},(_,i)=>({id:i+1,title:'I love you ❤️',file:`videos/${String(i+2).padStart(2,'0')}-memory-${i+1}.mp4`}));

function show(id){
  const next=document.querySelector(`#${id}`), current=document.querySelector('.screen.active');
  if(current===next)return;
  if(current){if(document.fullscreenElement&&current.contains(document.fullscreenElement))document.exitFullscreen?.().catch(()=>{});current.querySelectorAll('video').forEach(video=>{if(!video.ended){video.pause();video.currentTime=0}});gsap.to(current,{opacity:0,duration:.35,onComplete:()=>{current.classList.remove('active');current.style.opacity=''}});}
  next.classList.add('active'); gsap.fromTo(next,{opacity:0,y:14},{opacity:1,y:0,duration:.6,delay:.15,ease:'power2.out'});
  if(id==='loading') runLoading(); if(id==='intro') typeText('intro-text','This is not just a birthday surprise. It is a small reminder that your existence makes my world softer, brighter, and infinitely more beautiful.',()=>document.querySelector('#intro .text-btn').classList.remove('hidden'));
  if(id==='letter') typeText('letter-text',`Happiest 19th Birthday my lovee 🥳🥳❤️❤️

Toh finally apka wait over hua hai humne apka surprise apko de diya hai jo aap abhi padh rahe hai toh phele toh apko happy birthday 🥳🥳

Toh humne kuch alag karne kaa socha tha fir humko yaad aya ki apko website wala idea apko bhoat acha laga tha toh mai nai socha iss baar ek achi si website banate hai jo phele ki tarha boring nahi ho toh humne try toh kara hai isko acha banane ka i hope apko acha bhi laga ho or bataiye ga apko apka phela edit kesa laga vese humare pass aaj kuch khene ke liye toh nahi hai par hum apka yeh birthday ek memory jesa banana chate the jismai sab kuch apki achi achi photos ho apki pyari pyari videos ho toh humne ismai sab add kara hai mujhe pata hai mai kuch bhi bole jaa raha hu kyu ki mujhe kuch samjh nahi aa raha mai kya bolu iss letter mai par jab mai yeh likh raha hu tab mai bhoat excited hu ki jab aap yeh dekhinge toh apka reaction kesa hoga i hope apko acha lage or again apko happy birthday my love plus pyari madam jii plus devi jii plus apki abhi kuchupuchu bane ki internship bhi chal rahi hai 😅😂. Chaliye hum zyada nahi bolte abhi toh ab dil tham kar beth jaiye apke aage ke surprise aa rahe hai continue kar or apne surprise ko aage bhadaiyee 🥳🥳

I lovee youu ❤️❤️`,()=>document.querySelector('#letter-next').classList.remove('hidden'));
  if(id==='transition') typeText('transition-text','You opened every little edit. Now, there is one final thing I have been waiting to show you.',()=>document.querySelector('#reveal-final').classList.remove('hidden'));
  if(id==='laughing') buildLaughs(); if(id==='ending') buildSky();
  if(id==='opener'){const video=document.querySelector('#opener-video'),starter=document.querySelector('#opener-start');starter.style.display='inline-block';video.muted=false;video.volume=1;video.play().catch(()=>{starter.style.display='inline-block'});if(video.requestFullscreen)video.requestFullscreen().catch(()=>{});else if(video.webkitEnterFullscreen)video.webkitEnterFullscreen();} if(id==='final-video'){const video=document.querySelector('#last-video');video.currentTime=0;video.muted=false;video.volume=1;video.play().catch(()=>{});if(video.requestFullscreen)video.requestFullscreen().catch(()=>{});else if(video.webkitEnterFullscreen)video.webkitEnterFullscreen();}
}
function typeText(elId,text,done){const el=document.getElementById(elId);el.textContent='';let n=0;const timer=setInterval(()=>{el.textContent+=text[n++]||'';if(n>text.length){clearInterval(timer);done?.()}},18)}
function runLoading(){const bar=document.querySelector('.progress-line span');gsap.fromTo(bar,{width:'0%'},{width:'100%',duration:2.2,ease:'power2.inOut',onComplete:()=>show('intro')})}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.go==='earphones')music.play().catch(()=>{});show(b.dataset.go)}));
document.querySelectorAll('video').forEach(v=>{v.addEventListener('playing',()=>{const hint=v.parentElement.querySelector('.video-fallback');if(hint)hint.style.display='none';if(v.id==='opener-video')document.querySelector('#opener-start').style.display='none'});v.addEventListener('ended',()=>{if(v.id==='opener-video'&&document.querySelector('#opener').classList.contains('active'))show('birthday');if(v.id==='last-video'&&document.querySelector('#final-video').classList.contains('active'))show('laughing')})});document.querySelector('#opener-start').addEventListener('click',()=>{const video=document.querySelector('#opener-video');video.muted=false;video.play().catch(()=>{})});
document.querySelector('#edit-checklist').innerHTML=cards.map(card=>`<button class="edit-status" id="edit-status-${card.id}" type="button"><b>✓</b> I LOVE YOU ♥</button>`).join('');document.querySelectorAll('#edit-checklist .edit-status').forEach((control,index)=>control.addEventListener('click',()=>openMemory(cards[index],control)));
const modal=document.querySelector('#video-modal'),memoryVideo=document.querySelector('#memory-video');
function openMemory(card,button){document.querySelector('#film-label').textContent=`Edit ${String(card.id).padStart(2,'0')} · I love you`;const hint=modal.querySelector('.video-fallback');hint.style.display='';document.querySelector('#memory-source').src=card.file;memoryVideo.load();modal.classList.add('open');modal.setAttribute('aria-hidden','false');memoryVideo.play().catch(()=>{});if(memoryVideo.requestFullscreen)memoryVideo.requestFullscreen().catch(()=>{});else if(memoryVideo.webkitEnterFullscreen)memoryVideo.webkitEnterFullscreen();const complete=()=>{watched.add(card.id);sessionStorage.setItem('birthday-edits-watched',JSON.stringify([...watched]));button.classList.add('watched');updateProgress();setTimeout(()=>{closeModal();showCompletion()},180);memoryVideo.removeEventListener('ended',complete)};memoryVideo.addEventListener('ended',complete)}
function closeModal(){memoryVideo.pause();if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}document.querySelector('.modal-close').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function updateProgress(){const n=Math.min(watched.size,cards.length);document.querySelector('#watched-count').textContent=n;document.querySelector('#progress-fill').style.width=`${n/cards.length*100}%`;cards.forEach(card=>document.querySelector(`#edit-status-${card.id}`).classList.toggle('checked',watched.has(card.id)));const lock=document.querySelector('#final-lock');if(n>=cards.length){lock.disabled=false;lock.innerHTML='❤️ One Last Surprise ❤️';lock.onclick=()=>show('transition')}}updateProgress();
function buildSky(){const sky=document.querySelector('#sky');if(sky.childElementCount)return;for(let i=0;i<70;i++){const s=document.createElement('i');s.className=i<18?'heart':i<42?'firefly':'star';s.textContent=s.className==='heart'?'♥':'✦';s.style.left=`${Math.random()*100}%`;s.style.top=`${Math.random()*100}%`;s.style.animationDelay=`-${Math.random()*8}s`;s.style.animationDuration=`${4+Math.random()*6}s`;sky.append(s)}}
function buildLaughs(){const sky=document.querySelector('#laughing-sky');if(sky.childElementCount)return;for(let i=0;i<46;i++){const e=document.createElement('i'),word=i%3===0;e.className=word?'laugh laugh-word':'laugh';e.textContent=word?'hehehe':'😂';e.style.left=`${Math.random()*100}%`;e.style.setProperty('--delay',`-${Math.random()*8}s`);e.style.setProperty('--duration',`${4+Math.random()*5}s`);sky.append(e)}}
function showCompletion(){const toast=document.querySelector('#completion-toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200)}
document.querySelector('#replay').onclick=()=>{sessionStorage.removeItem('birthday-edits-watched');watched.clear();document.querySelectorAll('.memory-card').forEach(e=>e.classList.remove('watched'));updateProgress();show('welcome')};
document.querySelector('#secret-heart').onclick=()=>document.querySelector('#secret-message').classList.toggle('show');
