const screens = [...document.querySelectorAll('.screen')];
const music = document.querySelector('#music');
const warmedVideos = new Set();
function warmVideo(file){if(warmedVideos.has(file))return;warmedVideos.add(file);const hint=document.createElement('link');hint.rel='preload';hint.as='video';hint.href=file;document.head.append(hint)}
const surprisePasscode='22082007',pinInput=document.querySelector('#pin-input'),pinDots=document.querySelector('#pin-dots'),pinMessage=document.querySelector('#pin-message'),lockCard=document.querySelector('#lock-card');let pin='';
function renderPin(){pinInput.value=pin;pinDots.textContent=Array.from({length:8},(_,i)=>i<pin.length?'●':'○').join(' ')}
function resetLock(){pin='';renderPin();lockCard.classList.remove('unlocked','wrong');pinMessage.textContent='Enter the code to reveal your surprise.'}
const countdownNumber=document.querySelector('#countdown-number'),countdownReveal=document.querySelector('#countdown-reveal'),countdownEyebrow=document.querySelector('#countdown-eyebrow'),countdownNext=document.querySelector('#countdown-next'),countdownParty=document.querySelector('#countdown-party');let countdownTimers=[];
function stopBirthdayCountdown(){countdownTimers.forEach(clearTimeout);countdownTimers=[];countdownParty.replaceChildren()}
function buildCountdownParty(){for(let i=0;i<60;i++){const bit=document.createElement('i');bit.className='countdown-confetti';bit.style.left=`${Math.random()*100}%`;bit.style.setProperty('--confetti',['#ffd86e','#ff8fba','#c7a2ff','#8ce1c2','#ffa569'][i%5]);bit.style.setProperty('--delay',`-${Math.random()*5}s`);bit.style.setProperty('--duration',`${3.7+Math.random()*2.8}s`);bit.style.setProperty('--drift',`${-110+Math.random()*220}px`);bit.style.setProperty('--rotate',`${Math.random()*130}deg`);countdownParty.append(bit)}for(let i=0;i<9;i++){const burst=document.createElement('i');burst.className='countdown-popper';burst.style.left=`${5+Math.random()*90}%`;burst.style.setProperty('--delay',`${Math.random()*1.4}s`);countdownParty.append(burst)}}
function countdownLater(callback,delay){countdownTimers.push(setTimeout(callback,delay))}
function runBirthdayCountdown(){stopBirthdayCountdown();countdownNumber.style.display='block';countdownNumber.textContent='3';countdownEyebrow.textContent='Get ready...';countdownReveal.classList.remove('show');countdownNext.classList.add('hidden');['2','1'].forEach((number,index)=>countdownLater(()=>{countdownNumber.textContent=number},(index+1)*950));countdownLater(()=>{countdownNumber.style.display='none';countdownEyebrow.textContent='Today is all about you';countdownReveal.classList.add('show');buildCountdownParty();countdownLater(()=>countdownNext.classList.remove('hidden'),800)},2900)}
function unlockSurprise(){if(pin!==surprisePasscode){pinMessage.textContent='That is not the right code... try again ♡';lockCard.classList.remove('wrong');void lockCard.offsetWidth;lockCard.classList.add('wrong');setTimeout(()=>{pin='';renderPin();lockCard.classList.remove('wrong')},650);return}pinMessage.textContent='Correct... unlocking your surprise ✦';lockCard.classList.add('unlocked');setTimeout(()=>show('birthday-countdown'),720)}
function usePinKey(key){if(key==='back'){pin=pin.slice(0,-1);renderPin();return}if(key==='clear'){pin='';renderPin();return}if(!/^\d$/.test(key)||pin.length>=8)return;pin+=key;renderPin();if(pin.length===8)unlockSurprise()}
document.querySelectorAll('[data-pin-key]').forEach(button=>button.addEventListener('click',()=>usePinKey(button.dataset.pinKey)));document.querySelectorAll('[data-pin-action]').forEach(button=>button.addEventListener('click',()=>usePinKey(button.dataset.pinAction)));document.addEventListener('keydown',event=>{if(!document.querySelector('#unlock').classList.contains('active'))return;if(/^\d$/.test(event.key)){event.preventDefault();usePinKey(event.key)}else if(event.key==='Backspace'){event.preventDefault();usePinKey('back')}else if(event.key==='Escape'){usePinKey('clear')}});
const cakeStage=document.querySelector('#cake-stage'),cakeNote=document.querySelector('#cake-note'),blowCandles=document.querySelector('#blow-candles'),cakeNext=document.querySelector('#cake-next'),cakeParty=document.querySelector('#cake-party');let cakePartyTimer;const birthdayMessages=['Happy birthday my lovee ❤️','Happy birthday madam ji 😊','Happy birthday devi jii 😅😂','Happy birthday cutieee ❤️😊'];
function resetCake(){cakeStage.classList.remove('blown');cakeNote.textContent='I lovee youu sooo much ❤️😊';blowCandles.disabled=false;blowCandles.style.display='flex';cakeNext.classList.add('hidden')}
blowCandles.addEventListener('click',()=>{if(cakeStage.classList.contains('blown'))return;cakeStage.classList.add('blown');blowCandles.disabled=true;cakeNote.textContent='Wish made... every candle is glowing for you ✦';setTimeout(()=>{blowCandles.style.display='none';cakeNext.classList.remove('hidden')},950)});
function stopCakeParty(){clearInterval(cakePartyTimer);cakeParty.replaceChildren()}
function addCakeBurst(){const burst=document.createElement('div'),firework=document.createElement('span'),spark=document.createElement('i'),emoji=document.createElement('span'),message=document.createElement('span');burst.className='party-burst';burst.style.left=`${8+Math.random()*84}%`;burst.style.top=`${12+Math.random()*68}%`;firework.className='party-firework';spark.setAttribute('aria-hidden','true');firework.append(spark);emoji.className='party-emoji';emoji.textContent='🥳';message.className='party-message';message.textContent=birthdayMessages[Math.floor(Math.random()*birthdayMessages.length)];burst.append(firework,emoji,message);cakeParty.append(burst);setTimeout(()=>burst.remove(),2050)}
function addCakeBackgroundEmojis(){for(let i=0;i<28;i++){const emoji=document.createElement('i');emoji.className='party-bg-emoji';emoji.textContent='🥳';emoji.style.left=`${Math.random()*100}%`;emoji.style.setProperty('--float-delay',`-${Math.random()*8}s`);emoji.style.setProperty('--float-duration',`${5+Math.random()*5}s`);cakeParty.append(emoji)}}
function startCakeParty(){stopCakeParty();addCakeBackgroundEmojis();for(let i=0;i<5;i++)setTimeout(addCakeBurst,i*180);cakePartyTimer=setInterval(addCakeBurst,780)}
blowCandles.addEventListener('click',()=>{if(cakeStage.classList.contains('blown'))startCakeParty()});
const feedbackForm=document.querySelector('#feedback-form'),feedbackStatus=document.querySelector('#feedback-status'),feedbackNext=document.querySelector('#feedback-next'),feedbackSend=feedbackForm.querySelector('button[type="submit"]');
feedbackForm.addEventListener('submit',async event=>{event.preventDefault();feedbackStatus.classList.remove('error');const message=feedbackForm.elements.message.value.trim();if(!message){feedbackStatus.classList.add('error');feedbackStatus.textContent='Please feedback form mai bataiyee apko kesa laga surprise.';document.querySelector('#feedback-message').focus();return}feedbackStatus.textContent='Sending your words...';feedbackSend.disabled=true;try{const response=await fetch(feedbackForm.action,{method:'POST',body:new FormData(feedbackForm),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Form submission failed');feedbackStatus.textContent='Thank you, my love. Your feedback reached me ♥';feedbackForm.reset();feedbackNext.classList.remove('hidden')}catch(error){feedbackStatus.classList.add('error');feedbackStatus.textContent='Could not send right now. Please try again once.';feedbackSend.disabled=false}});
const cameraPreview=document.querySelector('#camera-preview'),cameraPhoto=document.querySelector('#camera-photo'),cameraPlaceholder=document.querySelector('#camera-placeholder'),cameraStatus=document.querySelector('#camera-status'),openCameraButton=document.querySelector('#open-camera'),capturePhotoButton=document.querySelector('#capture-photo');let cameraStream;
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}cameraPreview.pause();cameraPreview.srcObject=null}
function resetCamera(){stopCamera();cameraPhoto.classList.remove('show');cameraPhoto.removeAttribute('src');cameraPreview.classList.remove('show');cameraPlaceholder.style.display='grid';openCameraButton.classList.remove('hidden');openCameraButton.disabled=false;capturePhotoButton.classList.add('hidden');capturePhotoButton.disabled=false;cameraStatus.textContent='Nothing is captured until you choose to take a photo.'}
openCameraButton.addEventListener('click',async()=>{if(!navigator.mediaDevices?.getUserMedia){cameraStatus.textContent='Camera permission was not allowed.';return}cameraStatus.textContent='Opening your front camera...';openCameraButton.disabled=true;try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});cameraPreview.srcObject=cameraStream;await cameraPreview.play();cameraPlaceholder.style.display='none';cameraPreview.classList.add('show');openCameraButton.classList.add('hidden');capturePhotoButton.classList.remove('hidden');cameraStatus.textContent='You look cutee! Tap “Take photo” when ready.'}catch(error){cameraStatus.textContent='Camera permission was not allowed.';openCameraButton.disabled=false}});
capturePhotoButton.addEventListener('click',()=>{if(!cameraStream)return;capturePhotoButton.disabled=true;const canvas=document.createElement('canvas');canvas.width=cameraPreview.videoWidth||720;canvas.height=cameraPreview.videoHeight||960;const context=canvas.getContext('2d');context.translate(canvas.width,0);context.scale(-1,1);context.drawImage(cameraPreview,0,0,canvas.width,canvas.height);canvas.toBlob(async blob=>{if(!blob){cameraStatus.textContent='Photo capture could not complete. Please try once more.';capturePhotoButton.disabled=false;return}stopCamera();cameraPreview.classList.remove('show');cameraPhoto.src=URL.createObjectURL(blob);cameraPhoto.classList.add('show');cameraStatus.textContent='Sending your cute photo to Yash automatically...';try{const data=new FormData();data.append('_subject','A cute birthday surprise photo');data.append('photo',blob,'birthday-memory.jpg');const response=await fetch('https://formspree.io/f/xoeakqly',{method:'POST',body:data,headers:{Accept:'application/json'}});if(!response.ok)throw new Error('Upload failed');cameraStatus.textContent='Photo sent successfully ♥ Now, measuring your cuteness!';setTimeout(()=>show('cuteness'),1300)}catch(error){cameraStatus.textContent='Photo could not upload. Please tap Open camera and try again.';openCameraButton.classList.remove('hidden');openCameraButton.disabled=false;capturePhotoButton.classList.add('hidden')}},'image/jpeg',.9)});
const tulipWorld=document.querySelector('#tulip-world'),gardenTulips=document.querySelector('#garden-tulips'),tulipContinue=document.querySelector('#tulip-continue'),tulipNext=document.querySelector('#tulip-next'),tulipEyebrow=document.querySelector('#tulip-eyebrow'),tulipTitle=document.querySelector('#tulip-title'),tulipNote=document.querySelector('#tulip-note');let tulipTimers=[];
function stopTulipTimers(){tulipTimers.forEach(clearTimeout);tulipTimers=[]}
function tulipLater(callback,delay){tulipTimers.push(setTimeout(callback,delay))}
function buildTulipGarden(){if(gardenTulips.childElementCount)return;for(let i=0;i<54;i++){const flower=document.createElement('i');flower.className='garden-tulip';flower.style.left=`${Math.random()*100}%`;flower.style.setProperty('--flower',['#f06da1','#dc8fff','#ffb15f','#ff89bb','#e85094'][i%5]);flower.style.setProperty('--sway',`${3+Math.random()*3}s`);flower.style.scale=`${.52+Math.random()*.95}`;gardenTulips.append(flower)}}
function runTulipStory(){stopTulipTimers();buildTulipGarden();tulipWorld.classList.remove('garden-ready','solo-ready');void tulipWorld.offsetWidth;tulipEyebrow.textContent='Just for you';tulipTitle.innerHTML='A little <em>tulip</em><br>for my love.';tulipNote.textContent='I loveee youu ❤️❤️';tulipContinue.classList.add('hidden');tulipNext.classList.add('hidden');tulipLater(()=>tulipWorld.classList.add('solo-ready'),120);tulipLater(()=>tulipContinue.classList.remove('hidden'),3700)}
tulipContinue.addEventListener('click',()=>{tulipContinue.classList.add('hidden');tulipEyebrow.textContent='For my beautiful princess';tulipTitle.innerHTML='A whole <em>garden</em><br>for you.';tulipNote.textContent='I loveeeeee youuuuuu soooooo muuchhhhh and happy birthday my loveee hehehe ❤️❤️😊';tulipWorld.classList.add('garden-ready');tulipLater(()=>tulipNext.classList.remove('hidden'),3000)});
const watched = new Set(JSON.parse(sessionStorage.getItem('birthday-edits-watched') || '[]'));
const assetVersion='20260819';
const cards = Array.from({length:16},(_,i)=>({id:i+1,title:'I love you ❤️',file:`videos/${String(i+2).padStart(2,'0')}-memory-${i+1}.mp4?v=${assetVersion}`})).filter(card=>card.id!==13);

function show(id){
  const next=document.querySelector(`#${id}`), current=document.querySelector('.screen.active');
  if(current===next)return;
  if(current?.id==='cake'&&id!=='cake')stopCakeParty();
  if(current?.id==='birthday-countdown'&&id!=='birthday-countdown')stopBirthdayCountdown();
  if(current?.id==='camera-surprise'&&id!=='camera-surprise')stopCamera();
  if(current?.id==='tulip-story'&&id!=='tulip-story')stopTulipTimers();
  if(current){if(document.fullscreenElement&&current.contains(document.fullscreenElement))document.exitFullscreen?.().catch(()=>{});current.querySelectorAll('video').forEach(video=>{if(!video.ended){video.pause();video.currentTime=0}});gsap.to(current,{opacity:0,duration:.35,onComplete:()=>{current.classList.remove('active');current.style.opacity=''}});}
  next.classList.add('active'); gsap.fromTo(next,{opacity:0,y:14},{opacity:1,y:0,duration:.6,delay:.15,ease:'power2.out'});
  if(id==='loading') runLoading(); if(id==='intro') typeText('intro-text','This is not just a birthday surprise. It is a small reminder that your existence makes my world softer, brighter, and infinitely more beautiful.',()=>document.querySelector('#intro .text-btn').classList.remove('hidden'));
  if(id==='earphones') warmVideo('videos/01-opener.mp4');
  if(id==='birthday-countdown') runBirthdayCountdown();
  if(id==='cake') resetCake();
  if(id==='camera-surprise') resetCamera();
  if(id==='tulip-story') runTulipStory();
  if(id==='gallery') warmVideo(cards[0].file);
  if(id==='transition') warmVideo('videos/17-final-surprise.mp4');
  if(id==='cuteness') runCutenessMeter();
  if(id==='letter') typeText('letter-text',`Happiest 19th Birthday my lovee 🥳🥳❤️❤️

Toh finally apka wait over hua hai humne apka surprise apko de diya hai jo aap abhi padh rahe hai toh phele toh apko happy birthday 🥳🥳

Toh humne kuch alag karne kaa socha tha fir humko yaad aya ki apko website wala idea apko bhoat acha laga tha.. toh mai nai socha iss baar ek achi si website banate hai jo phele ki tarha boring nahi ho.. toh humne try toh kara hai isko acha banane ka i hope apko acha bhi lage or bataiye ga apko apka phela edit kesa laga.. hum apka yeh birthday ek bhoat achi memory jesa banana chate the jismai sab kuch ho apki achi achi photos ho apki pyari pyari videos ho toh humne ismai sab add kara hai mujhe pata hai mai kuch bhi bole jaa raha hu hehe.

Toh jese ki aaj humari pyari madam jii ka birthday hai toh aaj hum unke bare mai batana chahinge ki humari madam ji kitni pyari hai achi hai or bhoat zyada beautiful bhi hai hehe or pata hai hai itni pyari hai ki vo kabhi kabhi flow flow mai bhoat acha acha bhi bol deti hai haina madam ji par acha acha bolte hai jab bhi flow flow mai bolte hai aap.. toh umm aap bola kariyee flow flow mai umm agar apko lag raha hai hum bhoat interested lag rahe hai toh haan hum hai bhoat zyada intrested hai aap kuch kare or hum usmai intrested na ho yeh possible hi nahi hai haina madam jii.. or pata hai madam jii nai humko change hone ko bola hai or tab se humne pura try kar naa shuru kar diya hai ki hum change ho jaye par pata nahi madam jii ko ab bhoat shyy shyy hota hai esa kyu hai madam jii??.. Vese agar apko or kuch bhi changes kar ne ho na aap humko bata dijiyee gaa hum vo bhi kar dinge par fir aap humko bata dijiye gaa ki hum kese insaan hai with (last word) hehehe.. vese toh humari madam jii ke bare mai batane ke liye bhoat kuch hai ki unki smile kitni achi hai jab vo smile karti hai tab humko bhi unki tarha aiiiiiii hojata haii jab vo shyy shyy hojate hai tab humko unki tarha aayee hojata hai unki eyes kitni achi hai jab vo itne pyar se dekhte hai tab vo itne pyare or cute cute lagte hai naa aiiiii + aayee.. humari madam jii hi itni achi hai naa unke bare mai jitna bataye utna kam hai isliye abhi hum zyada nahi bolte surprise aage bhi continue karna hai naa.. par jab mai yeh likh raha hu tab mai bhoat excited hu ki jab aap yeh dekhinge toh apka reaction kesa hoga i hope apko acha lage or again apko happy birthday my love plus pyari madam jii plus devi jii plus apki abhi kuchupuchu bane ki internship bhi chal rahi hai 😅😂. Chaliye hum zyada nahi bolte abhi.. toh ab dil tham kar beth jaiye apke aage ka surprise aa rahe hai continue kare or apne surprise ko aage bhadaiyee 🥳🥳

I lovee youu soo muchhh ❤️❤️`,()=>document.querySelector('#letter-next').classList.remove('hidden'));
  if(id==='transition') typeText('transition-text','You opened every little edit. Now, there is one final thing I have been waiting to show you.',()=>document.querySelector('#reveal-final').classList.remove('hidden'));
  if(id==='laughing') buildLaughs(); if(id==='ending') buildSky();
  if(id==='opener'){const video=document.querySelector('#opener-video'),starter=document.querySelector('#opener-start');starter.style.display='inline-block';video.muted=false;video.volume=1;video.play().catch(()=>{starter.style.display='inline-block'});if(video.requestFullscreen)video.requestFullscreen().catch(()=>{});else if(video.webkitEnterFullscreen)video.webkitEnterFullscreen();} if(id==='final-video'){const video=document.querySelector('#last-video');video.currentTime=0;video.muted=false;video.volume=1;video.play().catch(()=>{});if(video.requestFullscreen)video.requestFullscreen().catch(()=>{});else if(video.webkitEnterFullscreen)video.webkitEnterFullscreen();}
}
function typeText(elId,text,done){const el=document.getElementById(elId);el.textContent='';let n=0;const timer=setInterval(()=>{el.textContent+=text[n++]||'';if(n>text.length){clearInterval(timer);done?.()}},18)}
function runLoading(){const bar=document.querySelector('.progress-line span');gsap.fromTo(bar,{width:'0%'},{width:'100%',duration:2.2,ease:'power2.inOut',onComplete:()=>show('intro')})}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.go==='earphones')music.play().catch(()=>{});show(b.dataset.go)}));
document.querySelectorAll('video').forEach(v=>{v.addEventListener('playing',()=>{const hint=v.parentElement.querySelector('.video-fallback');if(hint)hint.style.display='none';if(v.id==='opener-video')document.querySelector('#opener-start').style.display='none'});v.addEventListener('ended',()=>{if(v.id==='opener-video'&&document.querySelector('#opener').classList.contains('active'))show('cuteness-intro');if(v.id==='last-video'&&document.querySelector('#final-video').classList.contains('active'))show('laughing')})});document.querySelector('#opener-start').addEventListener('click',()=>{const video=document.querySelector('#opener-video');video.muted=false;video.play().catch(()=>{})});
document.querySelector('#edit-checklist').innerHTML=cards.map(card=>`<button class="edit-status" id="edit-status-${card.id}" type="button"><b>✓</b> I LOVE YOU ♥</button>`).join('');document.querySelectorAll('#edit-checklist .edit-status').forEach((control,index)=>control.addEventListener('click',()=>openMemory(cards[index],control)));
const modal=document.querySelector('#video-modal'),memoryVideo=document.querySelector('#memory-video');
function openMemory(card,button){document.querySelector('#film-label').textContent=`Edit ${String(card.id).padStart(2,'0')} · I love you`;const hint=modal.querySelector('.video-fallback');hint.style.display='';document.querySelector('#memory-source').src=card.file;memoryVideo.load();modal.classList.add('open');modal.setAttribute('aria-hidden','false');memoryVideo.play().catch(()=>{});if(memoryVideo.requestFullscreen)memoryVideo.requestFullscreen().catch(()=>{});else if(memoryVideo.webkitEnterFullscreen)memoryVideo.webkitEnterFullscreen();const complete=()=>{watched.add(card.id);sessionStorage.setItem('birthday-edits-watched',JSON.stringify([...watched]));button.classList.add('watched');updateProgress();setTimeout(()=>{closeModal();showCompletion()},180);memoryVideo.removeEventListener('ended',complete)};memoryVideo.addEventListener('ended',complete)}
function closeModal(){memoryVideo.pause();if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}document.querySelector('.modal-close').onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
function updateProgress(){const n=cards.reduce((count,card)=>count+(watched.has(card.id)?1:0),0);document.querySelector('#watched-count').textContent=n;document.querySelector('#progress-fill').style.width=`${n/cards.length*100}%`;cards.forEach(card=>document.querySelector(`#edit-status-${card.id}`).classList.toggle('checked',watched.has(card.id)));const lock=document.querySelector('#final-lock');if(n>=cards.length){lock.disabled=false;lock.innerHTML='❤️ One Last Surprise ❤️';lock.onclick=()=>show('transition')}}updateProgress();
function buildSky(){const sky=document.querySelector('#sky');if(sky.childElementCount)return;for(let i=0;i<70;i++){const s=document.createElement('i');s.className=i<18?'heart':i<42?'firefly':'star';s.textContent=s.className==='heart'?'♥':'✦';s.style.left=`${Math.random()*100}%`;s.style.top=`${Math.random()*100}%`;s.style.animationDelay=`-${Math.random()*8}s`;s.style.animationDuration=`${4+Math.random()*6}s`;sky.append(s)}}
function buildLaughs(){const sky=document.querySelector('#laughing-sky');if(sky.childElementCount)return;for(let i=0;i<46;i++){const e=document.createElement('i'),word=i%3===0;e.className=word?'laugh laugh-word':'laugh';e.textContent=word?'hehehe':'😂';e.style.left=`${Math.random()*100}%`;e.style.setProperty('--delay',`-${Math.random()*8}s`);e.style.setProperty('--duration',`${4+Math.random()*5}s`);sky.append(e)}}
function showCompletion(){const toast=document.querySelector('#completion-toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200)}
let cutenessFrame;
function runCutenessMeter(){const scene=document.querySelector('#meter-scene'),fill=document.querySelector('#meter-fill'),number=document.querySelector('#meter-number'),face=document.querySelector('#meter-face'),status=document.querySelector('#meter-status'),result=document.querySelector('#meter-result'),next=document.querySelector('#cuteness-next');cancelAnimationFrame(cutenessFrame);scene.classList.remove('blasted','overload');fill.style.width='0%';number.textContent='0';face.textContent='🙂';status.textContent='Starting the cuteness scan...';result.classList.remove('show');next.classList.add('hidden');const started=performance.now(),duration=13200;function animate(now){const elapsed=now-started;if(elapsed<6200){const p=elapsed/6200,value=Math.floor(100*Math.pow(p,1.7));number.textContent=value;fill.style.width=`${value}%`;if(value<20){face.textContent='🙂';status.textContent='Starting very carefully...';}else if(value<50){face.textContent='😊';status.textContent='Okay... definitely adorable.';}else if(value<80){face.textContent='🥰';status.textContent='The cuteness is rising...';}else{face.textContent='😳';status.textContent='Almost at the meter limit!';}}else if(elapsed<duration){const p=(elapsed-6200)/(duration-6200),value=Math.min(100000,Math.floor(100*Math.pow(1000,p)));number.textContent=value.toLocaleString('en-IN');fill.style.width='100%';scene.classList.add('overload');if(value<1000){face.textContent='😳';status.textContent='Wait... why is it still going?!';}else if(value<15000){face.textContent='🫣';status.textContent='Cuteness overload incoming...';}else{face.textContent='🤯';status.textContent='METER CAN’T HANDLE THIS!';}}else{number.textContent='∞';face.textContent='💥';status.textContent='CUTENESS METER: DESTROYED!';scene.classList.remove('overload');scene.classList.add('blasted');result.classList.add('show');setTimeout(()=>next.classList.remove('hidden'),700);return;}cutenessFrame=requestAnimationFrame(animate)}cutenessFrame=requestAnimationFrame(animate)}
document.querySelector('#replay').onclick=()=>{sessionStorage.removeItem('birthday-edits-watched');watched.clear();document.querySelectorAll('.memory-card').forEach(e=>e.classList.remove('watched'));updateProgress();resetLock();show('unlock')};
document.querySelector('#secret-heart').onclick=()=>document.querySelector('#secret-message').classList.toggle('show');
